##**MODULES IMPORTED**

In [1]:
import pandas as pd
import numpy as np
import Recommenders as Recommenders
#inside this file used directly as code
#in sklearn everything is code and present in a module hence, we use it
 


##**DATASET LOADED**

In [7]:
dataf1=pd.read_csv("/content/triplets_file.csv")
dataf1.head()


index                                   user_id             song_id  \
0      0  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOAKIMP12A8C130995   
1      1  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBBMDR12A8C13253B   
2      2  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBXHDL12A81C204C0   
3      3  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBYHAJ12A6701BF1D   
4      4  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SODACBL12A8C13C273   

   listen_count  
0           1.0  
1           2.0  
2           1.0  
3           1.0  
4           1.0

In [8]:
dataf2=pd.read_csv("/content/song_data.csv")
dataf2.head()
#song id is the common key to combine two dataset

song_id              title  \
0  SOQMMHC12AB0180CB8       Silent Night   
1  SOVFVAK12A8C1350D9        Tanssi vaan   
2  SOGTUKN12AB017F4F1  No One Could Ever   
3  SOBNYVR12A8C13558C      Si Vos Querés   
4  SOHSBXH12A8C13B0DF   Tangle Of Aspens   

                                release       artist_name    year  
0                 Monster Ballads X-Mas  Faster Pussy cat  2003.0  
1                           Karkuteillä  Karkkiautomaatti  1995.0  
2                                Butter    Hudson Mohawke  2006.0  
3                               De Culo       Yerba Brava  2003.0  
4  Rene Ablaze Presents Winter Sessions        Der Mystic     0.0

In [9]:
 song_df =pd.merge(dataf1,dataf2.drop_duplicates(['song_id']),on='song_id',how='left')
 #based on the left column both data frames will be combined on common column song_id 
 #dropping duplicates with same name of song_id from second dataset 
 song_df.head()

index                                   user_id             song_id  \
0      0  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOAKIMP12A8C130995   
1      1  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBBMDR12A8C13253B   
2      2  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBXHDL12A81C204C0   
3      3  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBYHAJ12A6701BF1D   
4      4  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SODACBL12A8C13C273   

   listen_count            title              release    artist_name    year  
0           1.0         The Cove   Thicker Than Water   Jack Johnson     0.0  
1           2.0  Entre Dos Aguas  Flamenco Para Niños  Paco De Lucia  1976.0  
2           1.0         Stronger           Graduation     Kanye West  2007.0  
3           1.0              NaN                  NaN            NaN     NaN  
4           1.0              NaN                  NaN            NaN     NaN

In [10]:

len(song_df) 

211127

##**DATA PREPROCESSING**
KEYWORDS CREATRED

In [11]:
#artist and title combined to create single song keyword
# creating new feature combining title and artist name
song_df['song']=song_df['title']+" - "+song_df['artist_name']


In [12]:
song_df=song_df.head(10000) #limiting dataset

In [13]:
#aggrigate listen count to get count of all the songs and create another data frame
#cummulative sum of listen count of the songs
#another dataframe created song_grouped 
song_grouped=song_df.groupby(['song']).agg({'listen_count':'count'}).reset_index()
song_grouped.head()

song  listen_count
0                           #40 - DAVE MATTHEWS BAND             1
1                        '97 Bonnie & Clyde - Eminem             2
2            (Anaesthesia) Pulling Teath - Metallica             1
3  (You Drive Me) Crazy (The Stop Remix!) - Britn...             2
4                           14 Years - Guns N' Roses             1

In [14]:
#taking perscentage
grouped_sum=song_grouped['listen_count'].sum() #all sum taken
song_grouped['percentage']=(song_grouped['listen_count']/grouped_sum)*100 #creating individual perscentage
#values sorted based on listen count if two song have same listen count then ascending order they are sorted
song_grouped.sort_values(['listen_count','song'],ascending=[0,1]) 


song  listen_count  \
2338                                       Undo - Björk            32   
2562                     You're The One - Dwight Yoakam            32   
536   Dog Days Are Over (Radio Edit) - Florence + Th...            28   
2181                           The Scientist - Coldplay            27   
2358                       Use Somebody - Kings Of Leon            27   
...                                                 ...           ...   
2578                          Zero - The Pain Machinery             1   
2580             Zopf: Pigtail - Penguin Café Orchestra             1   
2583                              high fives - Four Tet             1   
2585             paranoid android - Christopher O'Riley             1   
2589                              Época - Gotan Project             1   

      percentage  
2338    0.634669  
2562    0.634669  
536     0.555335  
2181    0.535502  
2358    0.535502  
...          ...  
2578    0.019833  
2580    0.019833  
2583    0.019833  
2585    0.019833  
2589    0.019833  

[2590 rows x 3 columns]

##**POPULARITY RECOMMENDATION ENGINE**

In [15]:
pr = Recommenders.popularity_recommender_py()
#behind  any ml model there will be algorithm for training testing which will be used by end user
#we can change the things in the file

In [16]:
pr.create(song_df,'user_id','song')

In [17]:
pr.recommend(song_df['user_id'][5]) #here 5 is the specific user for which the songs are being recommended
#based on the score rank is given and top 10 songs are recommended 

user_id  \
2338  b80344d063b5ccb3212f76538f3d9e43d87dca9e   
2562  b80344d063b5ccb3212f76538f3d9e43d87dca9e   
536   b80344d063b5ccb3212f76538f3d9e43d87dca9e   
2181  b80344d063b5ccb3212f76538f3d9e43d87dca9e   
2358  b80344d063b5ccb3212f76538f3d9e43d87dca9e   
2525  b80344d063b5ccb3212f76538f3d9e43d87dca9e   
1288  b80344d063b5ccb3212f76538f3d9e43d87dca9e   
378   b80344d063b5ccb3212f76538f3d9e43d87dca9e   
1142  b80344d063b5ccb3212f76538f3d9e43d87dca9e   
1925  b80344d063b5ccb3212f76538f3d9e43d87dca9e   

                                                   song  score  Rank  
2338                                       Undo - Björk     32   1.0  
2562                     You're The One - Dwight Yoakam     32   2.0  
536   Dog Days Are Over (Radio Edit) - Florence + Th...     28   3.0  
2181                           The Scientist - Coldplay     27   4.0  
2358                       Use Somebody - Kings Of Leon     27   5.0  
2525                                  Yellow - Coldplay     22   6.0  
1288  Lucky (Album Version) - Jason Mraz & Colbie Ca...     20   7.0  
378   Catch You Baby (Steve Pitron & Max Sanna Radio...     17   8.0  
1142             Just Dance - Lady GaGa / Colby O'Donis     17   9.0  
1925                   Somebody To Love - Justin Bieber     17  10.0

In [18]:
pr.recommend(song_df['user_id'][10])
#similarly for user no 10 
#the result for both the users will be same since it is popularity recommendation system trending songs


user_id  \
2338  b80344d063b5ccb3212f76538f3d9e43d87dca9e   
2562  b80344d063b5ccb3212f76538f3d9e43d87dca9e   
536   b80344d063b5ccb3212f76538f3d9e43d87dca9e   
2181  b80344d063b5ccb3212f76538f3d9e43d87dca9e   
2358  b80344d063b5ccb3212f76538f3d9e43d87dca9e   
2525  b80344d063b5ccb3212f76538f3d9e43d87dca9e   
1288  b80344d063b5ccb3212f76538f3d9e43d87dca9e   
378   b80344d063b5ccb3212f76538f3d9e43d87dca9e   
1142  b80344d063b5ccb3212f76538f3d9e43d87dca9e   
1925  b80344d063b5ccb3212f76538f3d9e43d87dca9e   

                                                   song  score  Rank  
2338                                       Undo - Björk     32   1.0  
2562                     You're The One - Dwight Yoakam     32   2.0  
536   Dog Days Are Over (Radio Edit) - Florence + Th...     28   3.0  
2181                           The Scientist - Coldplay     27   4.0  
2358                       Use Somebody - Kings Of Leon     27   5.0  
2525                                  Yellow - Coldplay     22   6.0  
1288  Lucky (Album Version) - Jason Mraz & Colbie Ca...     20   7.0  
378   Catch You Baby (Steve Pitron & Max Sanna Radio...     17   8.0  
1142             Just Dance - Lady GaGa / Colby O'Donis     17   9.0  
1925                   Somebody To Love - Justin Bieber     17  10.0

##**USER SIMILARITY RECOMMENDATION**

In [19]:
ir=Recommenders.item_similarity_recommender_py()
ir.create(song_df,'user_id','song')

In [20]:
user_items=ir.get_user_items(song_df['user_id'][5])

In [21]:
print(user_items)

['The Cove - Jack Johnson', 'Entre Dos Aguas - Paco De Lucia', 'Stronger - Kanye West', nan, 'Paper Gangsta - Lady GaGa', "Heaven's gonna burn your eyes - Thievery Corporation feat. Emiliana Torrini", 'Let It Be Sung - Jack Johnson / Matt Costa / Zach Gill / Dan Lebowitz / Steve Adams', "I'll Be Missing You (Featuring Faith Evans & 112)(Album Version) - Puff Daddy", "Love Shack - The B-52's", 'The Old Saloon - The Lonely Island', 'Behind The Sea [Live In Chicago] - Panic At The Disco', 'Champion - Kanye West', 'Country Road - Jack Johnson / Paula Fuga', 'Oh No - Andrew Bird', 'Love Song For No One - John Mayer', 'The Middle - Jimmy Eat World', 'The Christmas Song  (LP Version) - King Curtis', 'Drive - Incubus', 'Sun Giant - Fleet Foxes', 'Right Back - Sublime', 'Holes To Heaven - Jack Johnson']


In [22]:
for user_item in user_items:         #display user song history
  print(user_item)
##this will show diff result for diff user depending upon what they listen to

The Cove - Jack Johnson
Entre Dos Aguas - Paco De Lucia
Stronger - Kanye West
nan
Paper Gangsta - Lady GaGa
Heaven's gonna burn your eyes - Thievery Corporation feat. Emiliana Torrini
Let It Be Sung - Jack Johnson / Matt Costa / Zach Gill / Dan Lebowitz / Steve Adams
I'll Be Missing You (Featuring Faith Evans & 112)(Album Version) - Puff Daddy
Love Shack - The B-52's
The Old Saloon - The Lonely Island
Behind The Sea [Live In Chicago] - Panic At The Disco
Champion - Kanye West
Country Road - Jack Johnson / Paula Fuga
Oh No - Andrew Bird
Love Song For No One - John Mayer
The Middle - Jimmy Eat World
The Christmas Song  (LP Version) - King Curtis
Drive - Incubus
Sun Giant - Fleet Foxes
Right Back - Sublime
Holes To Heaven - Jack Johnson


In [23]:
ir.recommend(song_df['user_id'][5])
#user-user similarity
#matrix vuild on user history and all unique songs in dataset
#recommended songs based on the listened and total available song based on score and rank
#limiting dataset it will give different results for one user


No. of unique songs for the user: 21
no. of unique songs in the training set: 2591
Non zero values in cooccurence_matrix :1448


user_id  \
0  b80344d063b5ccb3212f76538f3d9e43d87dca9e   
1  b80344d063b5ccb3212f76538f3d9e43d87dca9e   
2  b80344d063b5ccb3212f76538f3d9e43d87dca9e   
3  b80344d063b5ccb3212f76538f3d9e43d87dca9e   
4  b80344d063b5ccb3212f76538f3d9e43d87dca9e   
5  b80344d063b5ccb3212f76538f3d9e43d87dca9e   
6  b80344d063b5ccb3212f76538f3d9e43d87dca9e   
7  b80344d063b5ccb3212f76538f3d9e43d87dca9e   
8  b80344d063b5ccb3212f76538f3d9e43d87dca9e   
9  b80344d063b5ccb3212f76538f3d9e43d87dca9e   

                                          song     score rank  
0                Everyone's At It - Lily Allen  0.040136    1  
1          Whataya Want From Me - Adam Lambert  0.035414    2  
2           Drunken Lullabies - Flogging Molly  0.034184    3  
3          Stuck In The Moment - Justin Bieber  0.033730    4  
4  Johnny_ I Hardly Knew Ya - Dropkick Murphys  0.033333    5  
5                           Up - Justin Bieber  0.033333    6  
6                  Eye Of The Tiger - Survivor  0.033107    7  
7               ROCKSTAR 101 - Rihanna / Slash  0.032785    8  
8                      Love Me - Justin Bieber  0.031746    9  
9              Here Without You - 3 Doors Down  0.031746   10

##**ITEM SIMILARITY RECOMMENDER**

In [24]:
#give songs related to words
ir.get_similar_items(['U Smile - Justin Bieber','Ddiamondd-Battles'])
#item similarity

no. of unique songs in the training set: 2591
Non zero values in cooccurence_matrix :167


user_id                                            song     score rank
0                     Stuck In The Moment - Justin Bieber  0.250000    1
1                   Bad Company - Five Finger Death Punch  0.187500    2
2                        Somebody To Love - Justin Bieber  0.176471    3
3                           Already Gone - Kelly Clarkson  0.166667    4
4          Eenie Meenie - Sean Kingston and Justin Bieber  0.166667    5
5                                   Paper Planes - M.I.A.  0.153846    6
6                                 Love Me - Justin Bieber  0.150000    7
7                                     Monster - Lady GaGa  0.150000    8
8                         Here Without You - 3 Doors Down  0.150000    9
9            The Funeral (Album Version) - Band Of Horses  0.150000   10

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
song_df.head()

index                                   user_id             song_id  \
0      0  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOAKIMP12A8C130995   
1      1  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBBMDR12A8C13253B   
2      2  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBXHDL12A81C204C0   
3      3  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBYHAJ12A6701BF1D   
4      4  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SODACBL12A8C13C273   

   listen_count            title              release    artist_name    year  \
0           1.0                                                          NaN   
1           2.0  Entre Dos Aguas  Flamenco Para Niños  Paco De Lucia  1976.0   
2           1.0                                                          NaN   
3           1.0                                                          NaN   
4           1.0                                                          NaN   

                            song  \
0                            NaN   
1  Entre Dos Aguas-Paco De Lucia   
2                            NaN   
3                            NaN   
4                            NaN   

                                   combined_features  
0                                 SOAKIMP12A8C130995  
1  Entre Dos Aguas Flamenco Para Niños Paco De Lu...  
2                                 SOBXHDL12A81C204C0  
3                                 SOBYHAJ12A6701BF1D  
4                                 SODACBL12A8C13C273

In [ ]:
features = ['title', 'release', 'artist_name', 'song_id']
for feature in features:
    song_df[feature] = song_df[feature].fillna('')

In [ ]:
def combined_features(row):
    return row['title']+" "+row['release']+" "+row['artist_name']+" "+row['song_id']
song_df["combined_features"] = song_df.apply(combined_features, axis =1)

In [ ]:
song_df.head()

index                                   user_id             song_id  \
0      0  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOAKIMP12A8C130995   
1      1  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBBMDR12A8C13253B   
2      2  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBXHDL12A81C204C0   
3      3  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBYHAJ12A6701BF1D   
4      4  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SODACBL12A8C13C273   

   listen_count            title              release    artist_name    year  \
0           1.0                                                          NaN   
1           2.0  Entre Dos Aguas  Flamenco Para Niños  Paco De Lucia  1976.0   
2           1.0                                                          NaN   
3           1.0                                                          NaN   
4           1.0                                                          NaN   

                            song  \
0                            NaN   
1  Entre Dos Aguas-Paco De Lucia   
2                            NaN   
3                            NaN   
4                            NaN   

                                   combined_features  
0                                 SOAKIMP12A8C130995  
1  Entre Dos Aguas Flamenco Para Niños Paco De Lu...  
2                                 SOBXHDL12A81C204C0  
3                                 SOBYHAJ12A6701BF1D  
4                                 SODACBL12A8C13C273

In [ ]:
cv = CountVectorizer()
count_matrix = cv.fit_transform(song_df["combined_features"])
print("Count Matrix:", count_matrix.toarray())

Count Matrix: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
cosine_sim = cosine_similarity(count_matrix)

In [ ]:
print(cosine_sim)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [ ]:
song_user_likes = "U Smile"
def get_index_from_title(title):
    return song_df[song_df.title == title]["index"]
song_index = get_index_from_title(song_user_likes)

In [ ]:
similar_songs = list(enumerate(cosine_sim[song_index]))

In [ ]:
sorted_similar_songs = sorted(similar_songs, key=lambda x:x[1], reverse=True)

In [ ]:
def get_title_from_index(index):
    return song_df[song_df.index == index]["title"].values[0]
i=0
for song in sorted_similar_songs:
    print(get_title_from_index(song[1]))
    i=i+1
    if i>15:
        break